application : hw5p2csc473
version : 3
runtime : python27
api_version : 1
threadsafe: true

handlers:
- url: /static
  static_dir: coreapp/static


- url: .*
  script : coreapp.app
libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest